markdown: rdiscount
pygments: true

info:
    title: Inspire IRCd
    slogan: The Stable, High-Performance and Modular IRCd
    uri: http://inspircd.github.com

meta:
    description: Inspire Internet Relay Chat Daemon is a modular, high performance IRC daemon combining stability and a rich and extensive C++ API with optional features such as SSL and permanent channels.
    keywords: inspircd, ircd, internet relay chat

navigation:
    - title: Home
      uri: /
    - title: Downloads
      uri: https://github.com/inspircd/inspircd/releases
    - title: Wiki
      uri: /wiki
    - title: Issue Tracker
      uri: https://github.com/inspircd/inspircd/issues
    - title: API
      uri: /api
    - title: Git
      uri: https://github.com/inspircd
